### ISSUE TITLE
Data Science in Education or Educational Data Science?

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#19]
I saw that some chapters refer to "data science in education" (Chapter 2) and some chapters refer to "educational data science" (Chapter 4: Unique Challenges). Are they the same thing? If yes, should we norm on one term? If no, should we have definitions for them early on?

**Comment by restrellado** [comment]
I just looked at it again and I think both are pointing to the same thing. I think "data science in education" is more precise because we're writing about doing data science *in the field of education*, versus doing data science *that can be described as educational*. On the other hand, every time I write "data science in education" it feels really ham-fisted. It's been really challenging getting sentences to sound right with that phrase. 

One thought might be to use "educational data science," but qualify what that really means up front.

**Comment by jrosen48** [comment]
Flagging that this came up in #27. I could go either way. Not to further complicate things, but if I think about teachers and students "doing data science," I wonder if that can be referred to as (a third term!) "data science education"?

**Comment by jkaupp** [comment]
I'd avoid "data science education" as most disciplines use "x education" as the development of teaching/pedagogy in that area. I think of it as applying the techniques and tools of whatever in an educational context. 

I think it would be beneficial to have that sort of clarifying statement early in the book.  Something like 

> By "Data science in education", we are meaning the application of the tools and techniques of data science and applying those in the context of education.

**Comment by restrellado** [comment]
We've made some progress on this discussion while working on the proposal. I'll close it for now.
