### ISSUE TITLE
Need corrections based on reader feedback

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#525]
10.7.1 Code chunk missing before the last paragraph.
10.7.2 Why do you use 'select_at' in the function, and not the vanilla 'select'?
10.7.4 Shouldn't the name of the dataset be child_counts?
10.8.2 "To answer that question, let’s start by making a new dataset that excludes any rows where the f variables has a value that is less than or equal to 500,000. " I think this should say "includes only rows where..."
12.4.3 The last paragraph ends abruptly - some text missing there?
13.7 Under Table 13.1: The text says: "The intercept’s value of 0.74 represents the percentage of points that students in the reference group class have." But, the value of the intercept is 73.20, and the DV is the grade, not percentage.
13.9 Last sentence "This shows that nearly 17% of the variability in the percentage of points students earned can be explained simply by knowing what class they are in." I'm not sure how this corresponds to the output above (but it might be just me not understanding ICCs).
14.8 I had to install the package "ranger" to run the ML model (this package was not included in the install list at the beginning of the chapter)
14.9 The text under Figure 14.1 doesn't quite correspond to what the figure is showing ("The second most important variable is the amount of time students spend in their course. The third most important variable is subjectFrScA" - the figure shows this in reverse)
15.4.1 Paragraph 1: error in citation ("Newton, 1991, p. @hbr2006")\

**Comment by restrellado** [comment]
Hey @jrosen48! I started looking into the feedback about chapter 13 and I think I'll defer to you on this one. Looks like the intercept in 13.7 was a typo–should be 73.20. 

Also in chapter 13, it looks like the word "percentage" is correct, since the values of `dat$final_grade` go from 0–100. I'd leave that part alone unless I'm missing something: 

>The intercept’s value of 0.74 represents the percentage of points that students in the reference group class have.

And finally, re: this 

>13.9 Last sentence "This shows that nearly 17% of the variability in the percentage of points students earned can be explained simply by knowing what class they are in." I'm not sure how this corresponds to the output above (but it might be just me not understanding ICCs).

. . . definitely should defer to you on this one. As best as I can tell, it looks like 17 percent refers back to the marginal R squared of `m_course`. So maybe the solution here is to move this sentence closer to table 13.4?

**Comment by jrosen48** [comment]
on it

**Comment by jrosen48** [comment]
thanks for triaging these
