### ISSUE TITLE
style guide for plots?

### ISSUE THREAD

**Issue by ivelasq** [data-edu/data-science-in-education#78]
Hi all! I've started making plots on a chapter. Would we be interested in having a style guide for ggplots? Happy to lead on creating one!

**Comment by ivelasq** [comment]
I created a palette and theme and saved them in the r folder. 
Let me know what you think and whether we should change it up!

**Comment by jkaupp** [comment]
I like the palette!  Checks out well on Viz Palette, with some minor conflicts with thin lines in red-green colorblindness.  I feel that including a complementary colour for singular highlights (and perhaps a muted grey) would be a good addition.

Theme font is difficult to select until those choices have been narrowed down for your print run.  I'm not a fan of Arial as a header.  Works well for a body text, but doesn't hold the same sort of punch for a heading due to the rounded body.   Really up to you, but I'd suggest a difference in weights if you go with the single font theme.

I'd also include more parameterization in the function,  so you have an easier time with modifications moving forward rather than repeated one-off `theme` calls.  Bob Rudis (hrbrmstr), has wonderful examples of these in https://github.com/hrbrmstr/hrbrthemes

**Comment by restrellado** [comment]
Palette is [here](https://github.com/data-edu/data-science-in-education/blob/master/r/palette_dataedu.R). Thank you @ivelasq !
